[build]
  publish = "frontend"
  command = "echo 'Static site - no build required'"

[[redirects]]
  from = "/api/v1/*"
  to = "https://cryptoclean-api.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
